--DROP TABLE IF EXISTS film_likes, film_genre, genre, film, film_rating, user_friends, film_user CASCADE;


CREATE TABLE IF NOT EXISTS film_user
(
    id           int generated by default as identity primary key,
    email        varchar(255) not null,
    login        varchar(255) not null,
    birthday     date not null,
    name         varchar(255)
);

CREATE TABLE IF NOT EXISTS user_friends
(
    id           int generated by default AS IDENTITY PRIMARY KEY,
    user_id      int REFERENCES film_user(id),
    friend_id    int REFERENCES film_user(id)
);

CREATE TABLE IF NOT EXISTS film_rating
(
    id           int generated by default as identity primary key,
    name         varchar(255) not null
);

CREATE TABLE IF NOT EXISTS film
(
    id            int generated by default as identity primary key,
    name          varchar(255) not null,
    description   varchar(1000) not null,
    release_date  date not null,
    duration      int not null,
    rating_id     int,
    CONSTRAINT fk_rating_id
            FOREIGN KEY (rating_id)
                REFERENCES film_rating (id)
);

CREATE TABLE IF NOT EXISTS genre
(
    id           int generated by default as identity primary key,
    name         varchar(255) not null
);

CREATE TABLE IF NOT EXISTS film_genre
(
    id           int generated by default as identity primary key,
    film_id      int REFERENCES film(id),
    genre_id     int REFERENCES genre(id)
);

CREATE TABLE IF NOT EXISTS film_likes
(
    id            int generated by default as identity primary key,
    film_id       int REFERENCES film(id),
    liked_user_id int REFERENCES film_user(id)
);

